import { checkPrimaryKeywordUniqueness } from "./guide-seo-validation";

export type GuideIntent = "informational" | "mixed" | "transactional";
export type GuideContentLevel = "full" | "lite";

export type CitySeo = {
  slug: string;
  name: string;
  country: string;
  days: number;
  description: string;
  highlights: string[];
  intent: GuideIntent;
  contentLevel: GuideContentLevel;
  primaryKeyword: string;
};

export const cityPages: CitySeo[] = [
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    days: 3,
    description:
      "A 3-day Paris travel guide focused on classic landmarks, cafe culture, and walkable neighborhoods.",
    highlights: ["Eiffel Tower", "Louvre Museum", "Montmartre"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Paris",
  },
  {
    slug: "barcelona",
    name: "Barcelona",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Barcelona travel guide packed with Gaudi architecture, beaches, and food markets.",
    highlights: ["Sagrada Familia", "Gothic Quarter", "La Boqueria"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Barcelona",
  },
  {
    slug: "london",
    name: "London",
    country: "United Kingdom",
    days: 3,
    description:
      "A 3-day London travel guide with iconic sights, museums, and neighborhoods across the Thames.",
    highlights: ["Westminster", "British Museum", "Tower Bridge"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in London",
  },
  {
    slug: "rome",
    name: "Rome",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Rome travel guide highlighting ancient history, piazzas, and Italian cuisine.",
    highlights: ["Colosseum", "Vatican Museums", "Trevi Fountain"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Rome",
  },
  {
    slug: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    days: 3,
    description:
      "A 3-day Lisbon travel guide focused on historic hills, river walks, and relaxed neighborhoods.",
    highlights: ["Alfama", "Belem", "Praca do Comercio"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Lisbon",
  },
  {
    slug: "prague",
    name: "Prague",
    country: "Czech Republic",
    days: 3,
    description:
      "A 3-day Prague travel guide covering the Old Town, castle views, and easy river strolls.",
    highlights: ["Old Town Square", "Charles Bridge", "Prague Castle"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Prague",
  },
  {
    slug: "vienna",
    name: "Vienna",
    country: "Austria",
    days: 3,
    description:
      "A 3-day Vienna travel guide pairing classic museums, palace gardens, and grand avenues.",
    highlights: ["St. Stephen's Cathedral", "Schonbrunn Palace", "MuseumsQuartier"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Vienna",
  },
  {
    slug: "budapest",
    name: "Budapest",
    country: "Hungary",
    days: 3,
    description:
      "A 3-day Budapest travel guide with Danube views, historic hills, and thermal baths.",
    highlights: ["Parliament", "Buda Castle", "Chain Bridge"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Budapest",
  },
  {
    slug: "seville",
    name: "Seville",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Seville travel guide centered on plazas, historic quarters, and riverside walks.",
    highlights: ["Seville Cathedral", "Plaza de Espana", "Barrio Santa Cruz"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Seville",
  },
  {
    slug: "berlin",
    name: "Berlin",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Berlin travel guide balancing history, creative neighborhoods, and relaxed parks.",
    highlights: ["Brandenburg Gate", "Museum Island", "East Side Gallery"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Berlin",
  },
  {
    slug: "florence",
    name: "Florence",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Florence travel guide focused on art, river walks, and Renaissance squares.",
    highlights: ["Duomo", "Uffizi Gallery", "Ponte Vecchio"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Florence",
  },
  {
    slug: "venice",
    name: "Venice",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Venice travel guide with canal strolls, classic churches, and slow island time.",
    highlights: ["St. Mark's Basilica", "Grand Canal", "Rialto Bridge"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Venice",
  },
  {
    slug: "milan",
    name: "Milan",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Milan travel guide mixing cathedral sights, design districts, and aperitivo stops.",
    highlights: ["Duomo di Milano", "Galleria Vittorio Emanuele II", "Navigli"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Milan",
  },
  {
    slug: "munich",
    name: "Munich",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Munich travel guide combining historic squares, garden breaks, and easy transit.",
    highlights: ["Marienplatz", "English Garden", "Nymphenburg Palace"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Munich",
  },
  {
    slug: "dublin",
    name: "Dublin",
    country: "Ireland",
    days: 3,
    description:
      "A 3-day Dublin travel guide with literary landmarks, cozy pubs, and riverside walks.",
    highlights: ["Trinity College", "Temple Bar", "St. Patrick's Cathedral"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Dublin",
  },
  {
    slug: "edinburgh",
    name: "Edinburgh",
    country: "United Kingdom",
    days: 3,
    description:
      "A 3-day Edinburgh travel guide featuring castle views, historic lanes, and scenic hikes.",
    highlights: ["Edinburgh Castle", "Royal Mile", "Arthur's Seat"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Edinburgh",
  },
  {
    slug: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    days: 3,
    description:
      "A 3-day Copenhagen travel guide focused on waterfront strolls, design, and bike-friendly routes.",
    highlights: ["Nyhavn", "Tivoli Gardens", "Rosenborg Castle"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Copenhagen",
  },
  {
    slug: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    days: 3,
    description:
      "A 3-day Stockholm travel guide with old town charm, museums, and island-hopping pauses.",
    highlights: ["Gamla Stan", "Vasa Museum", "Djurgarden"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Stockholm",
  },
  {
    slug: "athens",
    name: "Athens",
    country: "Greece",
    days: 3,
    description:
      "A 3-day Athens travel guide blending ancient sites, neighborhood cafes, and sunset viewpoints.",
    highlights: ["Acropolis", "Plaka", "Ancient Agora"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Athens",
  },
  {
    slug: "porto",
    name: "Porto",
    country: "Portugal",
    days: 3,
    description:
      "A 3-day Porto travel guide centered on riverside walks, historic lanes, and easy hilltop viewpoints.",
    highlights: ["Ribeira", "Dom Luis I Bridge", "Livraria Lello"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Porto",
  },
  {
    slug: "krakow",
    name: "Krakow",
    country: "Poland",
    days: 3,
    description:
      "A 3-day Krakow travel guide focused on the old town, castle hill, and calm neighborhood strolls.",
    highlights: ["Main Market Square", "Wawel Castle", "Kazimierz"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Krakow",
  },
  {
    slug: "zurich",
    name: "Zurich",
    country: "Switzerland",
    days: 3,
    description:
      "A 3-day Zurich travel guide mixing lakeside walks, compact museums, and relaxed old town time.",
    highlights: ["Lake Zurich", "Old Town", "Kunsthaus Zurich"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Zurich",
  },
  {
    slug: "brussels",
    name: "Brussels",
    country: "Belgium",
    days: 3,
    description:
      "A 3-day Brussels travel guide balancing grand squares, museum districts, and easy cafe breaks.",
    highlights: ["Grand Place", "Mont des Arts", "Royal Palace"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Brussels",
  },
  {
    slug: "valencia",
    name: "Valencia",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Valencia travel guide pairing old town sights, park strolls, and a relaxed beach afternoon.",
    highlights: ["City of Arts and Sciences", "Turia Gardens", "Central Market"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Valencia",
  },
  {
    slug: "oslo",
    name: "Oslo",
    country: "Norway",
    days: 3,
    description:
      "A 3-day Oslo travel guide focused on waterfront walks, compact museums, and quiet park time.",
    highlights: ["Aker Brygge", "Vigeland Park", "Oslo Opera House"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Oslo",
  },
  {
    slug: "reykjavik",
    name: "Reykjavik",
    country: "Iceland",
    days: 3,
    description:
      "A 3-day Reykjavik travel guide with walkable downtown stops, cozy cafes, and easy coastal views.",
    highlights: ["Hallgrimskirkja", "Harpa Concert Hall", "Old Harbor"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Reykjavik",
  },
  {
    slug: "istanbul",
    name: "Istanbul",
    country: "Turkey",
    days: 3,
    description:
      "A 3-day Istanbul travel guide blending historic core sights, ferry views, and layered neighborhoods.",
    highlights: ["Hagia Sophia", "Blue Mosque", "Grand Bazaar"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Istanbul",
  },
  {
    slug: "naples",
    name: "Naples",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Naples travel guide featuring historic streets, waterfront walks, and slow cafe time.",
    highlights: ["Spaccanapoli", "Castel dell'Ovo", "Naples National Archaeological Museum"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Naples",
  },
  {
    slug: "nice",
    name: "Nice",
    country: "France",
    days: 3,
    description:
      "A 3-day Nice travel guide centered on old town lanes, seaside promenades, and scenic viewpoints.",
    highlights: ["Promenade des Anglais", "Old Town", "Castle Hill"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Nice",
  },
  {
    slug: "warsaw",
    name: "Warsaw",
    country: "Poland",
    days: 3,
    description:
      "A 3-day Warsaw travel guide blending historic old town, modern districts, and river walks.",
    highlights: ["Old Town Square", "Royal Castle", "Lazienki Park"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Warsaw",
  },
  {
    slug: "granada",
    name: "Granada",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Granada travel guide focused on the Alhambra, historic quarters, and mountain views.",
    highlights: ["Alhambra", "Albaicin", "Generalife"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Granada",
  },
  {
    slug: "lyon",
    name: "Lyon",
    country: "France",
    days: 3,
    description:
      "A 3-day Lyon travel guide pairing Roman history, gastronomy, and riverside neighborhoods.",
    highlights: ["Vieux Lyon", "Fourviere Basilica", "Presqu'ile"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Lyon",
  },
  {
    slug: "salzburg",
    name: "Salzburg",
    country: "Austria",
    days: 3,
    description:
      "A 3-day Salzburg travel guide with baroque architecture, mountain views, and music heritage.",
    highlights: ["Hohensalzburg Fortress", "Mirabell Palace", "Old Town"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Salzburg",
  },
  {
    slug: "rotterdam",
    name: "Rotterdam",
    country: "Netherlands",
    days: 3,
    description:
      "A 3-day Rotterdam travel guide featuring modern architecture, waterfront walks, and cultural districts.",
    highlights: ["Erasmus Bridge", "Markthal", "Cube Houses"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Rotterdam",
  },
  {
    slug: "bergen",
    name: "Bergen",
    country: "Norway",
    days: 3,
    description:
      "A 3-day Bergen travel guide with fjord views, historic wharves, and mountain viewpoints.",
    highlights: ["Bryggen", "Fløyen", "Fish Market"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Bergen",
  },
  {
    slug: "bologna",
    name: "Bologna",
    country: "Italy",
    days: 2,
    description:
      "A 2-day Bologna travel guide focused on medieval towers, food markets, and university quarter walks.",
    highlights: ["Two Towers", "Piazza Maggiore", "Food Markets"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Bologna",
  },
  {
    slug: "bruges",
    name: "Bruges",
    country: "Belgium",
    days: 2,
    description:
      "A 2-day Bruges travel guide with canal strolls, medieval squares, and quiet cobblestone lanes.",
    highlights: ["Markt Square", "Belfry Tower", "Canal Tours"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Bruges",
  },
  {
    slug: "dubrovnik",
    name: "Dubrovnik",
    country: "Croatia",
    days: 3,
    description:
      "A 3-day Dubrovnik travel guide featuring historic walls, Adriatic views, and old town walks.",
    highlights: ["City Walls", "Old Town", "Lokrum Island"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Dubrovnik",
  },
  {
    slug: "helsinki",
    name: "Helsinki",
    country: "Finland",
    days: 3,
    description:
      "A 3-day Helsinki travel guide with waterfront design, island hopping, and relaxed cafe culture.",
    highlights: ["Helsinki Cathedral", "Suomenlinna", "Design District"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Helsinki",
  },
  {
    slug: "innsbruck",
    name: "Innsbruck",
    country: "Austria",
    days: 2,
    description:
      "A 2-day Innsbruck travel guide pairing alpine views, historic old town, and easy mountain access.",
    highlights: ["Golden Roof", "Nordkette", "Old Town"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Innsbruck",
  },
  {
    slug: "riga",
    name: "Riga",
    country: "Latvia",
    days: 2,
    description:
      "A 2-day Riga travel guide with art nouveau architecture, old town squares, and riverfront walks.",
    highlights: ["Old Town", "Art Nouveau District", "Daugava River"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Riga",
  },
  {
    slug: "split",
    name: "Split",
    country: "Croatia",
    days: 2,
    description:
      "A 2-day Split travel guide centered on Diocletian's Palace, waterfront promenades, and nearby islands.",
    highlights: ["Diocletian's Palace", "Riva Promenade", "Marjan Hill"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Split",
  },
  {
    slug: "tallinn",
    name: "Tallinn",
    country: "Estonia",
    days: 2,
    description:
      "A 2-day Tallinn travel guide featuring medieval old town, city walls, and harbor views.",
    highlights: ["Old Town", "Toompea Hill", "City Walls"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Tallinn",
  },
  {
    slug: "vilnius",
    name: "Vilnius",
    country: "Lithuania",
    days: 2,
    description:
      "A 2-day Vilnius travel guide with baroque architecture, historic lanes, and hilltop viewpoints.",
    highlights: ["Old Town", "Gediminas Tower", "Užupis"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Vilnius",
  },
  {
    slug: "tokyo",
    name: "Tokyo",
    country: "Japan",
    days: 3,
    description:
      "A 3-day Tokyo travel guide balancing traditional temples, modern districts, and exceptional food culture.",
    highlights: ["Senso-ji Temple", "Shibuya Crossing", "Tsukiji Market"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Tokyo",
  },
  {
    slug: "seoul",
    name: "Seoul",
    country: "South Korea",
    days: 3,
    description:
      "A 3-day Seoul travel guide mixing ancient palaces, modern neighborhoods, and dynamic street food scenes.",
    highlights: ["Gyeongbokgung Palace", "Myeongdong", "Bukchon Hanok Village"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Seoul",
  },
  {
    slug: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    days: 3,
    description:
      "A 3-day Bangkok travel guide featuring golden temples, floating markets, and vibrant street food.",
    highlights: ["Grand Palace", "Wat Pho", "Chatuchak Market"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Bangkok",
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    days: 3,
    description:
      "A 3-day Singapore travel guide combining modern architecture, diverse neighborhoods, and exceptional food.",
    highlights: ["Marina Bay", "Gardens by the Bay", "Chinatown"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Singapore",
  },
  {
    slug: "hong-kong",
    name: "Hong Kong",
    country: "China",
    days: 3,
    description:
      "A 3-day Hong Kong travel guide with skyline views, traditional markets, and easy island escapes.",
    highlights: ["Victoria Peak", "Star Ferry", "Temple Street Night Market"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Hong Kong",
  },
  {
    slug: "new-york",
    name: "New York",
    country: "USA",
    days: 3,
    description:
      "A 3-day New York travel guide covering iconic neighborhoods, world-class museums, and diverse food scenes.",
    highlights: ["Central Park", "Brooklyn Bridge", "Metropolitan Museum"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in New York",
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    country: "USA",
    days: 3,
    description:
      "A 3-day San Francisco travel guide featuring hillside neighborhoods, waterfront walks, and diverse cuisine.",
    highlights: ["Golden Gate Bridge", "Alcatraz", "Fisherman's Wharf"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in San Francisco",
  },
  {
    slug: "los-angeles",
    name: "Los Angeles",
    country: "USA",
    days: 3,
    description:
      "A 3-day Los Angeles travel guide balancing beaches, iconic neighborhoods, and relaxed coastal vibes.",
    highlights: ["Santa Monica Pier", "Griffith Observatory", "Venice Beach"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Los Angeles",
  },
  {
    slug: "sydney",
    name: "Sydney",
    country: "Australia",
    days: 3,
    description:
      "A 3-day Sydney travel guide with harbor views, coastal walks, and relaxed beach time.",
    highlights: ["Sydney Opera House", "Harbour Bridge", "Bondi Beach"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Sydney",
  },
  {
    slug: "melbourne",
    name: "Melbourne",
    country: "Australia",
    days: 3,
    description:
      "A 3-day Melbourne travel guide focused on laneway culture, coffee scenes, and easygoing neighborhoods.",
    highlights: ["Federation Square", "Queen Victoria Market", "St. Kilda"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Melbourne",
  },
  {
    slug: "dubai",
    name: "Dubai",
    country: "UAE",
    days: 3,
    description:
      "A 3-day Dubai travel guide pairing modern architecture, traditional souks, and desert experiences.",
    highlights: ["Burj Khalifa", "Dubai Mall", "Gold Souk"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Dubai",
  },
  {
    slug: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    days: 3,
    description:
      "A 3-day Marrakech travel guide featuring historic medinas, vibrant souks, and tranquil gardens.",
    highlights: ["Jemaa el-Fnaa", "Bahia Palace", "Majorelle Garden"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Marrakech",
  },
  {
    slug: "cairo",
    name: "Cairo",
    country: "Egypt",
    days: 3,
    description:
      "A 3-day Cairo travel guide with ancient pyramids, historic mosques, and bustling markets.",
    highlights: ["Pyramids of Giza", "Egyptian Museum", "Khan el-Khalili"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Cairo",
  },
  {
    slug: "buenos-aires",
    name: "Buenos Aires",
    country: "Argentina",
    days: 3,
    description:
      "A 3-day Buenos Aires travel guide mixing European architecture, tango culture, and vibrant neighborhoods.",
    highlights: ["La Boca", "Recoleta Cemetery", "San Telmo"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Buenos Aires",
  },
  {
    slug: "rio-de-janeiro",
    name: "Rio de Janeiro",
    country: "Brazil",
    days: 3,
    description:
      "A 3-day Rio de Janeiro travel guide featuring iconic beaches, mountain viewpoints, and vibrant culture.",
    highlights: ["Copacabana Beach", "Christ the Redeemer", "Sugarloaf Mountain"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Rio de Janeiro",
  },
  {
    slug: "mexico-city",
    name: "Mexico City",
    country: "Mexico",
    days: 3,
    description:
      "A 3-day Mexico City travel guide with historic centers, world-class museums, and exceptional food markets.",
    highlights: ["Zocalo", "Frida Kahlo Museum", "Xochimilco"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Mexico City",
  },
  {
    slug: "bucharest",
    name: "Bucharest",
    country: "Romania",
    days: 2,
    description:
      "A 2-day Bucharest travel guide pairing grand architecture, historic neighborhoods, and relaxed parks.",
    highlights: ["Palace of Parliament", "Old Town", "Herastrau Park"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Bucharest",
  },
  {
    slug: "sofia",
    name: "Sofia",
    country: "Bulgaria",
    days: 2,
    description:
      "A 2-day Sofia travel guide featuring historic churches, mountain views, and walkable city center.",
    highlights: ["Alexander Nevsky Cathedral", "Vitosha Mountain", "Serdika Complex"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Sofia",
  },
  {
    slug: "hamburg",
    name: "Hamburg",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Hamburg travel guide focused on harborfront walks, historic warehouses, and calm neighborhood strolls.",
    highlights: ["Speicherstadt", "Elbphilharmonie", "Alster Lakes"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Hamburg",
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    country: "Japan",
    days: 3,
    description:
      "A 3-day Kyoto travel guide centered on temples, gardens, and traditional neighborhoods.",
    highlights: ["Kiyomizu-dera", "Arashiyama", "Gion"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Kyoto",
  },
  {
    slug: "osaka",
    name: "Osaka",
    country: "Japan",
    days: 3,
    description:
      "A 3-day Osaka travel guide mixing street food districts, canal walks, and city landmarks.",
    highlights: ["Osaka Castle", "Dotonbori", "Kuromon Market"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Osaka",
  },
  {
    slug: "taipei",
    name: "Taipei",
    country: "Taiwan",
    days: 3,
    description:
      "A 3-day Taipei travel guide with temples, night markets, and easy city viewpoints.",
    highlights: ["Taipei 101", "Longshan Temple", "Ningxia Night Market"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Taipei",
  },
  {
    slug: "hanoi",
    name: "Hanoi",
    country: "Vietnam",
    days: 3,
    description:
      "A 3-day Hanoi travel guide focused on the Old Quarter, lake walks, and historic temples.",
    highlights: ["Hoan Kiem Lake", "Old Quarter", "Temple of Literature"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Hanoi",
  },
  {
    slug: "ho-chi-minh-city",
    name: "Ho Chi Minh City",
    country: "Vietnam",
    days: 3,
    description:
      "A 3-day Ho Chi Minh City travel guide featuring colonial landmarks, markets, and riverfront walks.",
    highlights: ["Ben Thanh Market", "Central Post Office", "Cholon"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Ho Chi Minh City",
  },
  {
    slug: "kuala-lumpur",
    name: "Kuala Lumpur",
    country: "Malaysia",
    days: 3,
    description:
      "A 3-day Kuala Lumpur travel guide balancing skyline views, cultural quarters, and night markets.",
    highlights: ["Petronas Towers", "Merdeka Square", "Jalan Alor"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Kuala Lumpur",
  },
  {
    slug: "jakarta",
    name: "Jakarta",
    country: "Indonesia",
    days: 3,
    description:
      "A 3-day Jakarta travel guide covering the old town, city monuments, and harbor views.",
    highlights: ["Kota Tua", "National Monument", "Sunda Kelapa Harbor"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Jakarta",
  },
  {
    slug: "manila",
    name: "Manila",
    country: "Philippines",
    days: 3,
    description:
      "A 3-day Manila travel guide focused on Intramuros, city museums, and bayfront walks.",
    highlights: ["Intramuros", "Rizal Park", "Manila Bay"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Manila",
  },
  {
    slug: "auckland",
    name: "Auckland",
    country: "New Zealand",
    days: 3,
    description:
      "A 3-day Auckland travel guide mixing harbor walks, volcanic viewpoints, and relaxed neighborhoods.",
    highlights: ["Sky Tower", "Viaduct Harbour", "Mount Eden"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Auckland",
  },
  {
    slug: "wellington",
    name: "Wellington",
    country: "New Zealand",
    days: 3,
    description:
      "A 3-day Wellington travel guide with waterfront strolls, museums, and compact neighborhoods.",
    highlights: ["Te Papa", "Wellington Waterfront", "Cable Car"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Wellington",
  },
  {
    slug: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    days: 3,
    description:
      "A 3-day Cape Town travel guide featuring Table Mountain views, waterfront walks, and colorful neighborhoods.",
    highlights: ["Table Mountain", "V&A Waterfront", "Bo-Kaap"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Cape Town",
  },
  {
    slug: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    days: 3,
    description:
      "A 3-day Nairobi travel guide pairing city museums, parks, and nearby wildlife experiences.",
    highlights: ["Nairobi National Park", "Nairobi National Museum", "Karura Forest"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Nairobi",
  },
  {
    slug: "casablanca",
    name: "Casablanca",
    country: "Morocco",
    days: 3,
    description:
      "A 3-day Casablanca travel guide with Atlantic coastline walks, art deco streets, and historic quarters.",
    highlights: ["Hassan II Mosque", "Corniche", "Habous Quarter"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Casablanca",
  },
  {
    slug: "accra",
    name: "Accra",
    country: "Ghana",
    days: 3,
    description:
      "A 3-day Accra travel guide focused on independence landmarks, coastal walks, and local markets.",
    highlights: ["Independence Square", "Jamestown", "Osu"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Accra",
  },
  {
    slug: "lima",
    name: "Lima",
    country: "Peru",
    days: 3,
    description:
      "A 3-day Lima travel guide combining historic plazas, clifftop walks, and art districts.",
    highlights: ["Plaza Mayor", "Miraflores", "Barranco"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Lima",
  },
  {
    slug: "cusco",
    name: "Cusco",
    country: "Peru",
    days: 3,
    description:
      "A 3-day Cusco travel guide centered on Inca heritage, stone lanes, and hilltop views.",
    highlights: ["Plaza de Armas", "Sacsayhuaman", "San Blas"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Cusco",
  },
  {
    slug: "cartagena",
    name: "Cartagena",
    country: "Colombia",
    days: 3,
    description:
      "A 3-day Cartagena travel guide focused on the walled city, colorful plazas, and coastal walks.",
    highlights: ["Walled City", "Castillo San Felipe", "Getsemani"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Cartagena",
  },
  {
    slug: "santiago",
    name: "Santiago",
    country: "Chile",
    days: 3,
    description:
      "A 3-day Santiago travel guide with hilltop viewpoints, historic plazas, and calm neighborhoods.",
    highlights: ["Cerro San Cristobal", "Plaza de Armas", "Lastarria"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Santiago",
  },
  {
    slug: "medellin",
    name: "Medellin",
    country: "Colombia",
    days: 3,
    description:
      "A 3-day Medellin travel guide featuring neighborhood walks, urban parks, and cultural stops.",
    highlights: ["Plaza Botero", "Comuna 13", "Botanical Garden"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Medellin",
  },
  {
    slug: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    days: 3,
    description:
      "A 3-day Amsterdam travel guide focused on canals, museums, and walkable neighborhoods.",
    highlights: ["Canal Ring", "Rijksmuseum", "Jordaan"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Amsterdam",
  },
  {
    slug: "madrid",
    name: "Madrid",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Madrid travel guide with royal sights, art museums, and relaxed tapas evenings.",
    highlights: ["Prado Museum", "Royal Palace", "Retiro Park"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Madrid",
  },
  {
    slug: "montreal",
    name: "Montreal",
    country: "Canada",
    days: 3,
    description:
      "A 3-day Montreal travel guide blending old town charm, neighborhoods, and cafe culture.",
    highlights: ["Old Montreal", "Mount Royal", "Plateau Mont-Royal"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Montreal",
  },
  {
    slug: "vancouver",
    name: "Vancouver",
    country: "Canada",
    days: 3,
    description:
      "A 3-day Vancouver travel guide with waterfront walks, parks, and diverse neighborhoods.",
    highlights: ["Stanley Park", "Granville Island", "Gastown"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Vancouver",
  },
  {
    slug: "toronto",
    name: "Toronto",
    country: "Canada",
    days: 3,
    description:
      "A 3-day Toronto travel guide covering waterfront, museums, and walkable districts.",
    highlights: ["CN Tower", "Distillery District", "St. Lawrence Market"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Toronto",
  },
  {
    slug: "chicago",
    name: "Chicago",
    country: "USA",
    days: 3,
    description:
      "A 3-day Chicago travel guide with lakefront walks, architecture, and relaxed neighborhoods.",
    highlights: ["Millennium Park", "Art Institute", "Riverwalk"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Chicago",
  },
  {
    slug: "boston",
    name: "Boston",
    country: "USA",
    days: 3,
    description:
      "A 3-day Boston travel guide focused on historic core, waterfront, and walkable streets.",
    highlights: ["Freedom Trail", "Faneuil Hall", "Back Bay"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Boston",
  },
  {
    slug: "washington-dc",
    name: "Washington DC",
    country: "USA",
    days: 3,
    description:
      "A 3-day Washington DC travel guide with monuments, museums, and mall strolls.",
    highlights: ["National Mall", "Smithsonian", "Georgetown"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Washington DC",
  },
  {
    slug: "miami",
    name: "Miami",
    country: "USA",
    days: 3,
    description:
      "A 3-day Miami travel guide pairing beaches, art deco, and relaxed neighborhood time.",
    highlights: ["South Beach", "Wynwood", "Little Havana"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Miami",
  },
  {
    slug: "san-diego",
    name: "San Diego",
    country: "USA",
    days: 3,
    description:
      "A 3-day San Diego travel guide with waterfront, parks, and easy coastal pacing.",
    highlights: ["Balboa Park", "Gaslamp Quarter", "La Jolla"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in San Diego",
  },
  {
    slug: "quebec-city",
    name: "Quebec City",
    country: "Canada",
    days: 2,
    description:
      "A 2-day Quebec City travel guide centered on old town, ramparts, and walkable lanes.",
    highlights: ["Old Quebec", "Chateau Frontenac", "Plains of Abraham"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Quebec City",
  },
  {
    slug: "cologne",
    name: "Cologne",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Cologne travel guide with cathedral views, river walks, and relaxed neighborhoods.",
    highlights: ["Cologne Cathedral", "Old Town", "Rheinauhafen"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Cologne",
  },
  {
    slug: "antwerp",
    name: "Antwerp",
    country: "Belgium",
    days: 2,
    description:
      "A 2-day Antwerp travel guide with historic center, museums, and compact walks.",
    highlights: ["Cathedral of Our Lady", "Grote Markt", "MAS Museum"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Antwerp",
  },
  {
    slug: "marseille",
    name: "Marseille",
    country: "France",
    days: 3,
    description:
      "A 3-day Marseille travel guide featuring old port, coastal views, and relaxed neighborhoods.",
    highlights: ["Vieux-Port", "Notre-Dame de la Garde", "Le Panier"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Marseille",
  },
  {
    slug: "bordeaux",
    name: "Bordeaux",
    country: "France",
    days: 3,
    description:
      "A 3-day Bordeaux travel guide with riverside walks, wine culture, and calm neighborhoods.",
    highlights: ["Place de la Bourse", "Saint-Pierre", "La Cité du Vin"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Bordeaux",
  },
  {
    slug: "turin",
    name: "Turin",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Turin travel guide with royal squares, museums, and cafe-lined arcades.",
    highlights: ["Mole Antonelliana", "Piazza Castello", "Egyptian Museum"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Turin",
  },
  {
    slug: "ljubljana",
    name: "Ljubljana",
    country: "Slovenia",
    days: 2,
    description:
      "A 2-day Ljubljana travel guide with castle views, river walks, and compact old town.",
    highlights: ["Ljubljana Castle", "Triple Bridge", "Preseren Square"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Ljubljana",
  },
  {
    slug: "geneva",
    name: "Geneva",
    country: "Switzerland",
    days: 2,
    description:
      "A 2-day Geneva travel guide with lake views, compact center, and relaxed pacing.",
    highlights: ["Jet d'Eau", "Old Town", "Lake Geneva"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Geneva",
  },
  {
    slug: "strasbourg",
    name: "Strasbourg",
    country: "France",
    days: 2,
    description:
      "A 2-day Strasbourg travel guide with cathedral, canals, and walkable old town.",
    highlights: ["Strasbourg Cathedral", "La Petite France", "Grande Île"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Strasbourg",
  },
  {
    slug: "bilbao",
    name: "Bilbao",
    country: "Spain",
    days: 2,
    description:
      "A 2-day Bilbao travel guide focused on Guggenheim, riverside, and compact old town.",
    highlights: ["Guggenheim Museum", "Casco Viejo", "Ria de Bilbao"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Bilbao",
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    country: "India",
    days: 3,
    description:
      "A 3-day Mumbai travel guide featuring Gateway of India, Marine Drive, and vibrant markets.",
    highlights: ["Gateway of India", "Marine Drive", "Colaba Causeway"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Mumbai",
  },
  {
    slug: "shanghai",
    name: "Shanghai",
    country: "China",
    days: 3,
    description:
      "A 3-day Shanghai travel guide with the Bund, French Concession, and modern skyline views.",
    highlights: ["The Bund", "French Concession", "Yu Garden"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Shanghai",
  },
  {
    slug: "tel-aviv",
    name: "Tel Aviv",
    country: "Israel",
    days: 3,
    description:
      "A 3-day Tel Aviv travel guide combining beaches, Bauhaus architecture, and vibrant nightlife.",
    highlights: ["Beach Promenade", "Old Jaffa", "Bauhaus Architecture"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Tel Aviv",
  },
  {
    slug: "jerusalem",
    name: "Jerusalem",
    country: "Israel",
    days: 3,
    description:
      "A 3-day Jerusalem travel guide focused on the Old City, religious sites, and historic markets.",
    highlights: ["Old City", "Western Wall", "Mount of Olives"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Jerusalem",
  },
  {
    slug: "bogota",
    name: "Bogota",
    country: "Colombia",
    days: 3,
    description:
      "A 3-day Bogota travel guide with La Candelaria, Monserrate, and vibrant food markets.",
    highlights: ["La Candelaria", "Monserrate", "Gold Museum"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Bogota",
  },
  {
    slug: "fez",
    name: "Fez",
    country: "Morocco",
    days: 2,
    description:
      "A 2-day Fez travel guide centered on the historic medina, tanneries, and artisan workshops.",
    highlights: ["Fes el-Bali", "Chouara Tannery", "Al-Attarine Madrasa"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Fez",
  },
  {
    slug: "chiang-mai",
    name: "Chiang Mai",
    country: "Thailand",
    days: 3,
    description:
      "A 3-day Chiang Mai travel guide featuring temples, old city walls, and Doi Suthep viewpoints.",
    highlights: ["Old City Temples", "Doi Suthep", "Sunday Walking Street"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Chiang Mai",
  },
  {
    slug: "siem-reap",
    name: "Siem Reap",
    country: "Cambodia",
    days: 2,
    description:
      "A 2-day Siem Reap travel guide focused on Angkor temples, old market, and Tonle Sap.",
    highlights: ["Angkor Wat", "Angkor Thom", "Pub Street"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Siem Reap",
  },
  {
    slug: "kathmandu",
    name: "Kathmandu",
    country: "Nepal",
    days: 3,
    description:
      "A 3-day Kathmandu travel guide with Durbar Square, Swayambhunath, and Thamel district.",
    highlights: ["Durbar Square", "Swayambhunath", "Boudhanath"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Kathmandu",
  },
  {
    slug: "colombo",
    name: "Colombo",
    country: "Sri Lanka",
    days: 3,
    description:
      "A 3-day Colombo travel guide featuring Fort district, Galle Face Green, and local markets.",
    highlights: ["Galle Face Green", "Fort District", "Gangaramaya Temple"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Colombo",
  },
  {
    slug: "seattle",
    name: "Seattle",
    country: "USA",
    days: 3,
    description:
      "A 3-day Seattle travel guide featuring waterfront walks, coffee culture, and scenic viewpoints.",
    highlights: ["Space Needle", "Pike Place Market", "Waterfront"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Seattle",
  },
  {
    slug: "nashville",
    name: "Nashville",
    country: "USA",
    days: 3,
    description:
      "A 3-day Nashville travel guide focused on music heritage, Southern food, and relaxed neighborhoods.",
    highlights: ["Country Music Hall of Fame", "Broadway", "The Gulch"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Nashville",
  },
  {
    slug: "new-orleans",
    name: "New Orleans",
    country: "USA",
    days: 3,
    description:
      "A 3-day New Orleans travel guide with French Quarter charm, jazz culture, and exceptional food.",
    highlights: ["French Quarter", "Jackson Square", "Garden District"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in New Orleans",
  },
  {
    slug: "phuket",
    name: "Phuket",
    country: "Thailand",
    days: 3,
    description:
      "A 3-day Phuket travel guide featuring beaches, old town charm, and coastal viewpoints.",
    highlights: ["Patong Beach", "Old Phuket Town", "Big Buddha"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Phuket",
  },
  {
    slug: "austin",
    name: "Austin",
    country: "USA",
    days: 3,
    description:
      "A 3-day Austin travel guide balancing live music, food scenes, and outdoor activities.",
    highlights: ["South Congress", "Barton Springs", "Live Music Venues"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Austin",
  },
  {
    slug: "lagos",
    name: "Lagos",
    country: "Nigeria",
    days: 3,
    description:
      "A 3-day Lagos travel guide featuring vibrant markets, coastal views, and cultural districts.",
    highlights: ["Victoria Island", "Lekki Conservation Centre", "National Museum"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Lagos",
  },
  {
    slug: "lahore",
    name: "Lahore",
    country: "Pakistan",
    days: 3,
    description:
      "A 3-day Lahore travel guide with Mughal architecture, historic forts, and vibrant food scenes.",
    highlights: ["Lahore Fort", "Badshahi Mosque", "Walled City"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Lahore",
  },
  {
    slug: "tbilisi",
    name: "Tbilisi",
    country: "Georgia",
    days: 3,
    description:
      "A 3-day Tbilisi travel guide blending old town charm, sulfur baths, and mountain viewpoints.",
    highlights: ["Old Tbilisi", "Narikala Fortress", "Bridge of Peace"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Tbilisi",
  },
  {
    slug: "yerevan",
    name: "Yerevan",
    country: "Armenia",
    days: 3,
    description:
      "A 3-day Yerevan travel guide featuring pink stone architecture, mountain views, and cultural sites.",
    highlights: ["Republic Square", "Cascade Complex", "Matenadaran"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Yerevan",
  },
  {
    slug: "baku",
    name: "Baku",
    country: "Azerbaijan",
    days: 3,
    description:
      "A 3-day Baku travel guide with Caspian Sea views, historic old town, and modern architecture.",
    highlights: ["Old City", "Flame Towers", "Caspian Waterfront"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Baku",
  },
  {
    slug: "portland",
    name: "Portland",
    country: "USA",
    days: 3,
    description:
      "A 3-day Portland travel guide featuring food scenes, craft culture, and relaxed neighborhood walks.",
    highlights: ["Powell's Books", "Food Carts", "Japanese Garden"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Portland",
  },
  {
    slug: "glasgow",
    name: "Glasgow",
    country: "United Kingdom",
    days: 3,
    description:
      "A 3-day Glasgow travel guide with Victorian architecture, art galleries, and vibrant street scenes.",
    highlights: ["Kelvingrove Art Gallery", "Glasgow Cathedral", "West End"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Glasgow",
  },
  {
    slug: "philadelphia",
    name: "Philadelphia",
    country: "USA",
    days: 3,
    description:
      "A 3-day Philadelphia travel guide covering historic landmarks, food markets, and walkable neighborhoods.",
    highlights: ["Independence Hall", "Reading Terminal Market", "Museum of Art"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Philadelphia",
  },
  {
    slug: "manchester",
    name: "Manchester",
    country: "United Kingdom",
    days: 3,
    description:
      "A 3-day Manchester travel guide mixing industrial heritage, music culture, and modern districts.",
    highlights: ["Northern Quarter", "Manchester Cathedral", "Science Museum"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Manchester",
  },
  {
    slug: "denver",
    name: "Denver",
    country: "USA",
    days: 3,
    description:
      "A 3-day Denver travel guide with mountain views, craft breweries, and relaxed urban walks.",
    highlights: ["Red Rocks", "Larimer Square", "Denver Art Museum"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Denver",
  },
  {
    slug: "sarajevo",
    name: "Sarajevo",
    country: "Bosnia and Herzegovina",
    days: 3,
    description:
      "A 3-day Sarajevo travel guide blending Ottoman heritage, historic bridges, and mountain viewpoints.",
    highlights: ["Baščaršija", "Latin Bridge", "Yellow Fortress"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Sarajevo",
  },
  {
    slug: "zagreb",
    name: "Zagreb",
    country: "Croatia",
    days: 3,
    description:
      "A 3-day Zagreb travel guide with historic upper town, green spaces, and relaxed cafe culture.",
    highlights: ["Upper Town", "Ban Jelačić Square", "Mirogoj Cemetery"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Zagreb",
  },
  {
    slug: "belgrade",
    name: "Belgrade",
    country: "Serbia",
    days: 3,
    description:
      "A 3-day Belgrade travel guide featuring fortress views, riverside walks, and vibrant nightlife districts.",
    highlights: ["Belgrade Fortress", "Skadarlija", "Kalemegdan Park"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Belgrade",
  },
  {
    slug: "bratislava",
    name: "Bratislava",
    country: "Slovakia",
    days: 2,
    description:
      "A 2-day Bratislava travel guide centered on the old town, castle views, and Danube walks.",
    highlights: ["Old Town", "Bratislava Castle", "Danube River"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Bratislava",
  },
  {
    slug: "luxembourg",
    name: "Luxembourg City",
    country: "Luxembourg",
    days: 2,
    description:
      "A 2-day Luxembourg City travel guide with fortress ruins, historic quarters, and scenic valley walks.",
    highlights: ["Old Fortress", "Grand Ducal Palace", "Grund District"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Luxembourg",
  },
  {
    slug: "delhi",
    name: "Delhi",
    country: "India",
    days: 3,
    description:
      "A 3-day Delhi travel guide featuring historic monuments, vibrant markets, and diverse neighborhoods.",
    highlights: ["Red Fort", "India Gate", "Jama Masjid"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Delhi",
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    country: "India",
    days: 3,
    description:
      "A 3-day Jaipur travel guide with royal palaces, historic forts, and colorful bazaars.",
    highlights: ["Amber Fort", "City Palace", "Hawa Mahal"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Jaipur",
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    country: "India",
    days: 2,
    description:
      "A 2-day Udaipur travel guide centered on lake views, palace grounds, and relaxed old town walks.",
    highlights: ["City Palace", "Lake Pichola", "Jag Mandir"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Udaipur",
  },
  {
    slug: "goa",
    name: "Goa",
    country: "India",
    days: 3,
    description:
      "A 3-day Goa travel guide balancing beaches, Portuguese heritage, and relaxed coastal vibes.",
    highlights: ["Beaches", "Old Goa", "Spice Plantations"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Goa",
  },
  {
    slug: "agra",
    name: "Agra",
    country: "India",
    days: 2,
    description:
      "A 2-day Agra travel guide focused on the Taj Mahal, historic forts, and Mughal architecture.",
    highlights: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Agra",
  },
  {
    slug: "amman",
    name: "Amman",
    country: "Jordan",
    days: 3,
    description:
      "A 3-day Amman travel guide blending ancient citadels, Roman ruins, and lively downtown souks.",
    highlights: ["Citadel", "Roman Theatre", "Downtown Souks"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Amman",
  },
  {
    slug: "quito",
    name: "Quito",
    country: "Ecuador",
    days: 3,
    description:
      "A 3-day Quito travel guide focused on the historic center, Andean viewpoints, and colonial plazas.",
    highlights: ["Old Town", "TelefériQo", "Basilica del Voto Nacional"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Quito",
  },
  {
    slug: "panama-city",
    name: "Panama City",
    country: "Panama",
    days: 3,
    description:
      "A 3-day Panama City travel guide pairing the canal, Casco Viejo, and waterfront walks.",
    highlights: ["Panama Canal", "Casco Viejo", "Cinta Costera"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Panama City",
  },
  {
    slug: "doha",
    name: "Doha",
    country: "Qatar",
    days: 3,
    description:
      "A 3-day Doha travel guide with modern museums, souks, and corniche strolls.",
    highlights: ["Museum of Islamic Art", "Souq Waqif", "Corniche"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Doha",
  },
  {
    slug: "oaxaca",
    name: "Oaxaca",
    country: "Mexico",
    days: 3,
    description:
      "A 3-day Oaxaca travel guide centered on colonial streets, markets, and nearby ruins.",
    highlights: ["Zócalo", "Monte Albán", "Mercado 20 de Noviembre"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Oaxaca",
  },
  {
    slug: "valletta",
    name: "Valletta",
    country: "Malta",
    days: 3,
    description:
      "A 3-day Valletta travel guide featuring historic fortifications, baroque architecture, and harbor views.",
    highlights: ["St. John's Co-Cathedral", "Grand Harbour", "Upper Barrakka Gardens"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Valletta",
  },
  {
    slug: "nicosia",
    name: "Nicosia",
    country: "Cyprus",
    days: 3,
    description:
      "A 3-day Nicosia travel guide blending historic walls, divided city views, and relaxed old town walks.",
    highlights: ["Ledra Street", "Cyprus Museum", "Venetian Walls"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Nicosia",
  },
  {
    slug: "skopje",
    name: "Skopje",
    country: "North Macedonia",
    days: 3,
    description:
      "A 3-day Skopje travel guide with historic bazaars, modern monuments, and mountain viewpoints.",
    highlights: ["Old Bazaar", "Stone Bridge", "Skopje Fortress"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Skopje",
  },
  {
    slug: "tirana",
    name: "Tirana",
    country: "Albania",
    days: 3,
    description:
      "A 3-day Tirana travel guide featuring colorful buildings, mountain views, and relaxed cafe culture.",
    highlights: ["Skanderbeg Square", "Bunk'Art", "Mount Dajti"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Tirana",
  },
  {
    slug: "podgorica",
    name: "Podgorica",
    country: "Montenegro",
    days: 3,
    description:
      "A 3-day Podgorica travel guide with river walks, historic bridges, and relaxed city center.",
    highlights: ["Millennium Bridge", "Old Town", "Ribnica River"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Podgorica",
  },
  {
    slug: "palermo",
    name: "Palermo",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Palermo travel guide focused on Sicilian heritage, baroque churches, and relaxed old town strolls.",
    highlights: ["Teatro Massimo", "Palermo Cathedral", "Quattro Canti"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Palermo",
  },
  {
    slug: "belfast",
    name: "Belfast",
    country: "United Kingdom",
    days: 3,
    description:
      "A 3-day Belfast travel guide with Titanic heritage, city hall, and waterfront walks.",
    highlights: ["Titanic Belfast", "City Hall", "Crumlin Road Gaol"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Belfast",
  },
  {
    slug: "malaga",
    name: "Malaga",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Malaga travel guide combining Picasso heritage, Alcazaba fortress, and Costa del Sol beaches.",
    highlights: ["Alcazaba", "Malaga Cathedral", "Picasso Museum"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Malaga",
  },
  {
    slug: "thessaloniki",
    name: "Thessaloniki",
    country: "Greece",
    days: 3,
    description:
      "A 3-day Thessaloniki travel guide with White Tower views, waterfront promenades, and Byzantine heritage.",
    highlights: ["White Tower", "Aristotelous Square", "Rotunda"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Thessaloniki",
  },
  {
    slug: "toulouse",
    name: "Toulouse",
    country: "France",
    days: 3,
    description:
      "A 3-day Toulouse travel guide featuring pink brick architecture, Garonne river walks, and aerospace heritage.",
    highlights: ["Capitole", "Basilica of Saint-Sernin", "Cité de l'Espace"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Toulouse",
  },
  {
    slug: "santorini",
    name: "Santorini",
    country: "Greece",
    days: 3,
    description:
      "A 3-day Santorini travel guide focused on caldera views, village strolls, and relaxed coastal pacing.",
    highlights: ["Oia sunset", "Fira caldera views", "Red Beach"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Santorini",
  },
  {
    slug: "cork",
    name: "Cork",
    country: "Ireland",
    days: 2,
    description:
      "A 2-day Cork travel guide with English Market, riverside walks, and compact city center.",
    highlights: ["English Market", "St. Fin Barre's Cathedral", "Shandon Bells"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Cork",
  },
  {
    slug: "palma-de-mallorca",
    name: "Palma de Mallorca",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Palma de Mallorca travel guide pairing cathedral sights, old town lanes, and waterfront strolls.",
    highlights: ["La Seu Cathedral", "Old Town", "Paseo Maritimo"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Palma de Mallorca",
  },
  {
    slug: "lille",
    name: "Lille",
    country: "France",
    days: 2,
    description:
      "A 2-day Lille travel guide with Grand Place, old town charm, and relaxed Flemish-style streets.",
    highlights: ["Grand Place", "Vieux Lille", "Palais des Beaux-Arts"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Lille",
  },
  {
    slug: "san-sebastian",
    name: "San Sebastián",
    country: "Spain",
    days: 3,
    description:
      "A 3-day San Sebastián travel guide focused on the bay, pintxos culture, and relaxed beach time.",
    highlights: ["La Concha Beach", "Parte Vieja", "Monte Urgull"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in San Sebastián",
  },
  {
    slug: "havana",
    name: "Havana",
    country: "Cuba",
    days: 3,
    description:
      "A 3-day Havana travel guide with colonial plazas, vintage cars, and relaxed waterfront strolls.",
    highlights: ["Old Havana", "Malecón", "Plaza de la Catedral"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Havana",
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    country: "India",
    days: 3,
    description:
      "A 3-day Kolkata travel guide blending colonial heritage, markets, and riverside walks.",
    highlights: ["Victoria Memorial", "Howrah Bridge", "Kumartuli"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Kolkata",
  },
  {
    slug: "liverpool",
    name: "Liverpool",
    country: "United Kingdom",
    days: 3,
    description:
      "A 3-day Liverpool travel guide with waterfront heritage, music history, and walkable neighborhoods.",
    highlights: ["Albert Dock", "The Beatles Story", "Cathedral"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Liverpool",
  },
  {
    slug: "las-vegas",
    name: "Las Vegas",
    country: "USA",
    days: 3,
    description:
      "A 3-day Las Vegas travel guide balancing the Strip, downtown, and relaxed pool or desert time.",
    highlights: ["The Strip", "Fremont Street", "Red Rock Canyon"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Las Vegas",
  },
  {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    days: 3,
    description:
      "A 3-day Bali travel guide with temples, rice terraces, and coastal villages.",
    highlights: ["Ubud", "Tanah Lot", "Seminyak"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Bali",
  },
  {
    slug: "verona",
    name: "Verona",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Verona travel guide focused on the historic center, arena, and Shakespeare-era streets.",
    highlights: ["Arena di Verona", "Juliet's House", "Piazza delle Erbe"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Verona",
  },
  {
    slug: "cancun",
    name: "Cancun",
    country: "Mexico",
    days: 3,
    description:
      "A 3-day Cancun travel guide balancing beach time, nearby ruins, and relaxed resort pacing.",
    highlights: ["Hotel Zone beaches", "Chichen Itza day trip", "Isla Mujeres"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Cancun",
  },
  {
    slug: "ibiza",
    name: "Ibiza",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Ibiza travel guide with old town charm, beaches, and calm coastal pacing.",
    highlights: ["Dalt Vila", "Beaches and coves", "Ibiza Town"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Ibiza",
  },
  {
    slug: "mykonos",
    name: "Mykonos",
    country: "Greece",
    days: 3,
    description:
      "A 3-day Mykonos travel guide featuring windmills, beaches, and relaxed island walks.",
    highlights: ["Mykonos Town", "Little Venice", "Beach coves"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Mykonos",
  },
  {
    slug: "bath",
    name: "Bath",
    country: "United Kingdom",
    days: 2,
    description:
      "A 2-day Bath travel guide centered on Roman baths, Georgian streets, and compact city walks.",
    highlights: ["Roman Baths", "Royal Crescent", "Bath Abbey"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "2 days in Bath",
  },
  {
    slug: "frankfurt",
    name: "Frankfurt",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Frankfurt travel guide mixing museums, riverside walks, and historic squares with calm pacing.",
    highlights: ["Romerberg", "Museum Embankment", "Old Opera"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Frankfurt",
  },
  {
    slug: "genoa",
    name: "Genoa",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Genoa travel guide focused on the historic port, caruggi lanes, and seaside views.",
    highlights: ["Old Port", "Palazzi dei Rolli", "Boccadasse"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Genoa",
  },
  {
    slug: "cordoba",
    name: "Córdoba",
    country: "Spain",
    days: 3,
    description:
      "A 3-day Córdoba travel guide centered on the Mezquita, Jewish Quarter, and Andalusian courtyards.",
    highlights: ["Mezquita-Cathedral", "Juderia", "Alcazar"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Córdoba",
  },
  {
    slug: "bristol",
    name: "Bristol",
    country: "United Kingdom",
    days: 3,
    description:
      "A 3-day Bristol travel guide with street art, harborside walks, and relaxed neighborhood pacing.",
    highlights: ["Clifton Suspension Bridge", "Harbourside", "SS Great Britain"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Bristol",
  },
  {
    slug: "gothenburg",
    name: "Gothenburg",
    country: "Sweden",
    days: 3,
    description:
      "A 3-day Gothenburg travel guide pairing canals, museums, and fika stops with easy tram links.",
    highlights: ["Haga", "Liseberg", "Feskekorka"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Gothenburg",
  },
  {
    slug: "luxor",
    name: "Luxor",
    country: "Egypt",
    days: 3,
    description:
      "A 3-day Luxor travel guide centered on ancient temples, the Valley of the Kings, and Nile views.",
    highlights: ["Karnak Temple", "Valley of the Kings", "Luxor Temple"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Luxor",
  },
  {
    slug: "riyadh",
    name: "Riyadh",
    country: "Saudi Arabia",
    days: 3,
    description:
      "A 3-day Riyadh travel guide mixing modern skyline, historic Diriyah, and relaxed souk strolls.",
    highlights: ["Kingdom Tower", "Diriyah", "National Museum"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Riyadh",
  },
  {
    slug: "bengaluru",
    name: "Bengaluru",
    country: "India",
    days: 3,
    description:
      "A 3-day Bengaluru travel guide focused on tech parks, gardens, and relaxed neighborhood cafes.",
    highlights: ["Cubbon Park", "Lalbagh Botanical Garden", "Bangalore Palace"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Bengaluru",
  },
  {
    slug: "muscat",
    name: "Muscat",
    country: "Oman",
    days: 3,
    description:
      "A 3-day Muscat travel guide with forts, souks, and coastal viewpoints along the Gulf of Oman.",
    highlights: ["Sultan Qaboos Grand Mosque", "Mutrah Souq", "Al Jalali Fort"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Muscat",
  },
  {
    slug: "kigali",
    name: "Kigali",
    country: "Rwanda",
    days: 3,
    description:
      "A 3-day Kigali travel guide featuring genocide memorials, hillside views, and relaxed cafe culture.",
    highlights: ["Kigali Genocide Memorial", "Kimironko Market", "Nyamirambo"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Kigali",
  },
  {
    slug: "kyiv",
    name: "Kyiv",
    country: "Ukraine",
    days: 3,
    description:
      "A 3-day Kyiv travel guide blending golden-domed churches, historic squares, and relaxed riverside walks.",
    highlights: ["St. Michael's Cathedral", "Maidan Nezalezhnosti", "Pechersk Lavra"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Kyiv",
  },
  {
    slug: "leipzig",
    name: "Leipzig",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Leipzig travel guide focused on historic squares, Bach heritage, and calm neighborhood strolls.",
    highlights: ["St. Thomas Church", "Market Square", "Grassimuseum"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Leipzig",
  },
  {
    slug: "wroclaw",
    name: "Wroclaw",
    country: "Poland",
    days: 3,
    description:
      "A 3-day Wroclaw travel guide with Market Square, dwarf statues, and easy riverfront walks.",
    highlights: ["Market Square", "Ostrów Tumski", "Centennial Hall"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Wroclaw",
  },
  {
    slug: "adelaide",
    name: "Adelaide",
    country: "Australia",
    days: 3,
    description:
      "A 3-day Adelaide travel guide pairing parklands, wine regions, and relaxed city-center walks.",
    highlights: ["North Terrace", "Adelaide Central Market", "Glenelg"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Adelaide",
  },
  {
    slug: "guadalajara",
    name: "Guadalajara",
    country: "Mexico",
    days: 3,
    description:
      "A 3-day Guadalajara travel guide centered on colonial plazas, mariachi culture, and tequila tastings.",
    highlights: ["Guadalajara Cathedral", "Hospicio Cabañas", "Tlaquepaque"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Guadalajara",
  },
  {
    slug: "detroit",
    name: "Detroit",
    country: "USA",
    days: 3,
    description:
      "A 3-day Detroit travel guide pairing museums, riverfront walks, and revived neighborhoods.",
    highlights: ["Motown Museum", "Detroit Institute of Arts", "Riverwalk"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Detroit",
  },
  {
    slug: "atlanta",
    name: "Atlanta",
    country: "USA",
    days: 3,
    description:
      "A 3-day Atlanta travel guide focused on history, parks, and Southern food.",
    highlights: ["Martin Luther King Jr. National Historical Park", "Piedmont Park", "Georgia Aquarium"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Atlanta",
  },
  {
    slug: "san-antonio",
    name: "San Antonio",
    country: "USA",
    days: 3,
    description:
      "A 3-day San Antonio travel guide with the River Walk, the Alamo, and relaxed pacing.",
    highlights: ["The Alamo", "River Walk", "Pearl District"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in San Antonio",
  },
  {
    slug: "calgary",
    name: "Calgary",
    country: "Canada",
    days: 3,
    description:
      "A 3-day Calgary travel guide mixing downtown sights, western heritage, and easy day-trip options.",
    highlights: ["Calgary Tower", "Heritage Park", "Stephen Avenue Walk"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Calgary",
  },
  {
    slug: "ottawa",
    name: "Ottawa",
    country: "Canada",
    days: 3,
    description:
      "A 3-day Ottawa travel guide covering Parliament Hill, canals, and museums at a calm pace.",
    highlights: ["Parliament Hill", "ByWard Market", "National Gallery"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Ottawa",
  },
  {
    slug: "gdansk",
    name: "Gdansk",
    country: "Poland",
    days: 3,
    description:
      "A 3-day Gdansk travel guide focused on the historic Long Market, maritime heritage, and Baltic waterfront walks.",
    highlights: ["Long Market", "Crane Gate", "Westerplatte"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Gdansk",
  },
  {
    slug: "lausanne",
    name: "Lausanne",
    country: "Switzerland",
    days: 2,
    description:
      "A 2-day Lausanne travel guide pairing lake views, Olympic heritage, and compact old town strolls.",
    highlights: ["Lake Geneva waterfront", "Olympic Museum", "Old Town"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Lausanne",
  },
  {
    slug: "cardiff",
    name: "Cardiff",
    country: "United Kingdom",
    days: 2,
    description:
      "A 2-day Cardiff travel guide with castle views, Victorian arcades, and relaxed bay walks.",
    highlights: ["Cardiff Castle", "Cardiff Bay", "Bute Park"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Cardiff",
  },
  {
    slug: "nantes",
    name: "Nantes",
    country: "France",
    days: 2,
    description:
      "A 2-day Nantes travel guide centered on the Château, Loire waterfront, and creative island stops.",
    highlights: ["Château des Ducs", "Machines de l'Île", "Passage Pommeraye"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Nantes",
  },
  {
    slug: "dresden",
    name: "Dresden",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Dresden travel guide blending baroque landmarks, Elbe views, and calm neighborhood walks.",
    highlights: ["Frauenkirche", "Zwinger", "Brühlsche Terrasse"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Dresden",
  },
  {
    slug: "brisbane",
    name: "Brisbane",
    country: "Australia",
    days: 3,
    description:
      "A 3-day Brisbane travel guide focused on the river, South Bank, and relaxed subtropical pace.",
    highlights: ["South Bank", "Story Bridge", "Lone Pine Koala Sanctuary"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Brisbane",
  },
  {
    slug: "phoenix",
    name: "Phoenix",
    country: "USA",
    days: 3,
    description:
      "A 3-day Phoenix travel guide mixing desert views, museums, and easy outdoor pacing.",
    highlights: ["Desert Botanical Garden", "Old Town Scottsdale", "Camelback Mountain"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Phoenix",
  },
  {
    slug: "nagoya",
    name: "Nagoya",
    country: "Japan",
    days: 3,
    description:
      "A 3-day Nagoya travel guide with castle, museums, and calm city-center walks.",
    highlights: ["Nagoya Castle", "Toyota Commemorative Museum", "Osu district"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Nagoya",
  },
  {
    slug: "busan",
    name: "Busan",
    country: "South Korea",
    days: 3,
    description:
      "A 3-day Busan travel guide featuring beaches, temples, and relaxed coastal pacing.",
    highlights: ["Haeundae Beach", "Gamcheon Village", "Jagalchi Market"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Busan",
  },
  {
    slug: "montevideo",
    name: "Montevideo",
    country: "Uruguay",
    days: 3,
    description:
      "A 3-day Montevideo travel guide centered on the Rambla, Ciudad Vieja, and cafe culture.",
    highlights: ["Rambla", "Ciudad Vieja", "Mercado del Puerto"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Montevideo",
  },
  {
    slug: "abu-dhabi",
    name: "Abu Dhabi",
    country: "UAE",
    days: 3,
    description:
      "A 3-day Abu Dhabi travel guide pairing grand mosques, waterfront promenades, and calm cultural stops.",
    highlights: ["Sheikh Zayed Grand Mosque", "Corniche", "Louvre Abu Dhabi"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Abu Dhabi",
  },
  {
    slug: "sao-paulo",
    name: "São Paulo",
    country: "Brazil",
    days: 3,
    description:
      "A 3-day São Paulo travel guide focused on museums, diverse neighborhoods, and relaxed food scenes.",
    highlights: ["Paulista Avenue", "Ibirapuera Park", "Mercado Municipal"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in São Paulo",
  },
  {
    slug: "honolulu",
    name: "Honolulu",
    country: "USA",
    days: 3,
    description:
      "A 3-day Honolulu travel guide with historic sites, beaches, and easy coastal pacing.",
    highlights: ["Pearl Harbor", "Waikiki Beach", "Diamond Head"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Honolulu",
  },
  {
    slug: "sapporo",
    name: "Sapporo",
    country: "Japan",
    days: 3,
    description:
      "A 3-day Sapporo travel guide blending food markets, parks, and relaxed winter-city vibes.",
    highlights: ["Odori Park", "Nijo Market", "Sapporo Beer Museum"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Sapporo",
  },
  {
    slug: "perth",
    name: "Perth",
    country: "Australia",
    days: 3,
    description:
      "A 3-day Perth travel guide with waterfront walks, parks, and relaxed west-coast pacing.",
    highlights: ["Kings Park", "Fremantle", "Swan River"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Perth",
  },
  {
    slug: "funchal",
    name: "Funchal",
    country: "Portugal",
    days: 3,
    description:
      "A 3-day Funchal travel guide with gardens, old town, and relaxed Madeira pacing.",
    highlights: ["Monte Palace Gardens", "Old Town", "Cable car and levada walks"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Funchal",
  },
  {
    slug: "kotor",
    name: "Kotor",
    country: "Montenegro",
    days: 3,
    description:
      "A 3-day Kotor travel guide covering the bay, old town, and fortress with calm pacing.",
    highlights: ["Old Town", "Fortress climb", "Bay of Kotor"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Kotor",
  },
  {
    slug: "rovinj",
    name: "Rovinj",
    country: "Croatia",
    days: 3,
    description:
      "A 3-day Rovinj travel guide with old town, harbor, and coastal walks.",
    highlights: ["Old Town", "Church of St. Euphemia", "Harbor and islands"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Rovinj",
  },
  {
    slug: "brasov",
    name: "Brasov",
    country: "Romania",
    days: 3,
    description:
      "A 3-day Brasov travel guide for Transylvania's gateway: old town, fortress, and mountain views.",
    highlights: ["Old Town", "Black Church", "Nearby castles and views"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Brasov",
  },
  {
    slug: "mostar",
    name: "Mostar",
    country: "Bosnia and Herzegovina",
    days: 2,
    description:
      "A 2-day Mostar travel guide focused on the bridge, old town, and relaxed pacing.",
    highlights: ["Stari Most", "Old Bazaar", "Old Town streets"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "2 days in Mostar",
  },
  {
    slug: "cincinnati",
    name: "Cincinnati",
    country: "USA",
    days: 3,
    description:
      "A 3-day Cincinnati travel guide with riverfront walks, historic neighborhoods, and relaxed Midwest pacing.",
    highlights: ["Findlay Market", "Smale Riverfront Park", "Over-the-Rhine"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Cincinnati",
  },
  {
    slug: "pittsburgh",
    name: "Pittsburgh",
    country: "USA",
    days: 3,
    description:
      "A 3-day Pittsburgh travel guide blending bridges, museums, and neighborhood food scenes.",
    highlights: ["Point State Park", "Carnegie Museums", "Strip District"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Pittsburgh",
  },
  {
    slug: "chennai",
    name: "Chennai",
    country: "India",
    days: 3,
    description:
      "A 3-day Chennai travel guide focused on temples, beaches, and South Indian food culture.",
    highlights: ["Kapaleeshwarar Temple", "Marina Beach", "Mylapore"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Chennai",
  },
  {
    slug: "san-juan",
    name: "San Juan",
    country: "Puerto Rico",
    days: 3,
    description:
      "A 3-day San Juan travel guide with colonial old town, fort views, and relaxed coastal pacing.",
    highlights: ["Old San Juan", "El Morro", "Condado"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in San Juan",
  },
  {
    slug: "tampa",
    name: "Tampa",
    country: "USA",
    days: 3,
    description:
      "A 3-day Tampa travel guide pairing waterfront walks, historic Ybor City, and easy beach time.",
    highlights: ["Riverwalk", "Ybor City", "St. Pete Beach"],
    intent: "mixed",
    contentLevel: "lite",
    primaryKeyword: "3 days in Tampa",
  },
  {
    slug: "stuttgart",
    name: "Stuttgart",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Stuttgart travel guide with automotive heritage, parks, and calm city-center walks.",
    highlights: ["Mercedes-Benz Museum", "Schlossplatz", "Wilhelma"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Stuttgart",
  },
  {
    slug: "nuremberg",
    name: "Nuremberg",
    country: "Germany",
    days: 3,
    description:
      "A 3-day Nuremberg travel guide featuring the old town, castle, and historic squares.",
    highlights: ["Imperial Castle", "Old Town", "Hauptmarkt"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Nuremberg",
  },
  {
    slug: "galway",
    name: "Galway",
    country: "Ireland",
    days: 3,
    description:
      "A 3-day Galway travel guide with colorful streets, live music, and coastal day trips.",
    highlights: ["Latin Quarter", "Spanish Arch", "Salthill"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Galway",
  },
  {
    slug: "cannes",
    name: "Cannes",
    country: "France",
    days: 3,
    description:
      "A 3-day Cannes travel guide pairing the Croisette, old town, and relaxed Riviera pacing.",
    highlights: ["La Croisette", "Le Suquet", "Iles de Lérins"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Cannes",
  },
  {
    slug: "catania",
    name: "Catania",
    country: "Italy",
    days: 3,
    description:
      "A 3-day Catania travel guide with baroque streets, Mount Etna views, and Sicilian food.",
    highlights: ["Piazza del Duomo", "Via Etnea", "Fish market"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Catania",
  },
  {
    slug: "dakar",
    name: "Dakar",
    country: "Senegal",
    days: 3,
    description:
      "A 3-day Dakar travel guide with coastal views, markets, and island day trips at a relaxed pace.",
    highlights: ["Goree Island", "African Renaissance Monument", "Marché Kermel"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Dakar",
  },
  {
    slug: "johannesburg",
    name: "Johannesburg",
    country: "South Africa",
    days: 3,
    description:
      "A 3-day Johannesburg travel guide pairing museums, neighborhoods, and nearby sights with calm pacing.",
    highlights: ["Apartheid Museum", "Constitution Hill", "Soweto"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Johannesburg",
  },
  {
    slug: "minneapolis",
    name: "Minneapolis",
    country: "USA",
    days: 3,
    description:
      "A 3-day Minneapolis travel guide with lakes, arts, and walkable neighborhoods at a relaxed pace.",
    highlights: ["Stone Arch Bridge", "Walker Art Center", "Minneapolis Sculpture Garden"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Minneapolis",
  },
  {
    slug: "santo-domingo",
    name: "Santo Domingo",
    country: "Dominican Republic",
    days: 3,
    description:
      "A 3-day Santo Domingo travel guide focused on the colonial zone, waterfront, and local culture.",
    highlights: ["Zona Colonial", "Alcázar de Colón", "Malecón"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Santo Domingo",
  },
  {
    slug: "tunis",
    name: "Tunis",
    country: "Tunisia",
    days: 3,
    description:
      "A 3-day Tunis travel guide with medina lanes, Bardo Museum, and nearby Carthage at a calm pace.",
    highlights: ["Medina of Tunis", "Bardo Museum", "Carthage"],
    intent: "mixed",
    contentLevel: "full",
    primaryKeyword: "3 days in Tunis",
  },
];

export function getCityBySlug(slug: string): CitySeo | undefined {
  return cityPages.find((city) => city.slug === slug);
}

if (process.env.NODE_ENV !== "production") {
  checkPrimaryKeywordUniqueness(cityPages);
}
