"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Plus, Share2, Users, ArrowLeft, MoreVertical, Trash2, Loader2, Send, MapPin, Star, Check, X } from "lucide-react";
import { useTrip } from "@/hooks/use-trip";
import { useDays } from "@/hooks/use-days";
import { useActivities } from "@/hooks/use-activities";
import { DaySelector } from "@/components/day-selector";
import { ActivityList } from "@/components/activity-list";
import { ActivityDialog } from "@/components/activity-dialog";
import { format, formatDistanceToNow } from "date-fns";
import { ShareTripDialog } from "@/components/share-trip-dialog";
import { TripMembersDialog } from "@/components/trip-members-dialog";
import { DeleteTripDialog } from "@/components/delete-trip-dialog";
import { HotelSearchBanner } from "@/components/hotel-search-banner";
import { useRouter } from "next/navigation";
import { getDayRoute, RouteLeg } from "@/lib/mapboxDirections";
import { useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/components/ui/toast";
import { createClient } from "@/lib/supabase/client";
import type { AiItinerary, ActivitySuggestion } from "@/app/api/ai-itinerary/route";
import { getChatMessages, saveChatMessage, type ChatMessage } from "@/lib/supabase/trip-chat-messages";

/**
 * Check if a suggestion is an ActivitySuggestion object
 */
function isActivitySuggestion(suggestion: string | ActivitySuggestion): suggestion is ActivitySuggestion {
  return typeof suggestion === 'object' && suggestion !== null && 'title' in suggestion;
}

interface ItineraryTabProps {
  tripId: string;
  userId: string;
  selectedDayId: string | null;
  onSelectDay: (dayId: string) => void;
  onActivitySelect?: (activityId: string) => void;
}

export function ItineraryTab({
  tripId,
  userId,
  selectedDayId,
  onSelectDay,
  onActivitySelect,
}: ItineraryTabProps) {
  const [activityDialogOpen, setActivityDialogOpen] = useState(false);
  const [editingActivity, setEditingActivity] = useState<any>(null);
  const [shareDialogOpen, setShareDialogOpen] = useState(false);
  const [membersDialogOpen, setMembersDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [settingsMenuOpen, setSettingsMenuOpen] = useState(false);
  const [routeLegs, setRouteLegs] = useState<RouteLeg[]>([]);
  const [aiItinerary, setAiItinerary] = useState<AiItinerary | null>(null);
  const [loadingAiItinerary, setLoadingAiItinerary] = useState(false);
  const [aiItineraryError, setAiItineraryError] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);
  const [chatOpen] = useState(true); // Always open now
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [sendingChat, setSendingChat] = useState(false);
  const [chatHasMore, setChatHasMore] = useState(false);
  const [loadingChatMessages, setLoadingChatMessages] = useState(false);
  const chatMessagesEndRef = useRef<HTMLDivElement>(null);
  const chatContainerRef = useRef<HTMLDivElement>(null);
  const router = useRouter();
  const queryClient = useQueryClient();
  const { addToast } = useToast();
  const settingsMenuRef = useRef<HTMLDivElement>(null);
  const supabase = createClient();
  const [visitedPlaces, setVisitedPlaces] = useState<Set<string>>(new Set());

  const { data: trip, isLoading: tripLoading } = useTrip(tripId);
  const { data: days, isLoading: daysLoading } = useDays(tripId);
  const {
    activities,
    createActivity,
    updateActivity,
    deleteActivity,
    isLoading: activitiesLoading,
  } = useActivities(selectedDayId || "");
  const [allActivitiesCount, setAllActivitiesCount] = useState<number | null>(null);

  // Load existing itinerary from smart_itineraries table on mount
  useEffect(() => {
    if (!tripId || aiItinerary || loadingAiItinerary || hasAutoGenerated.current) return;

    const loadExistingItinerary = async () => {
      setLoadingAiItinerary(true);
      try {
        const response = await fetch("/api/ai-itinerary", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ tripId }),
        });

        if (response.ok) {
          const { itinerary } = await response.json();
          if (itinerary) {
            setAiItinerary(itinerary);
            hasAutoGenerated.current = true;
          }
        }
      } catch (error) {
        console.error("Error loading existing itinerary:", error);
        // Silently fail - will generate new one if needed
      } finally {
        setLoadingAiItinerary(false);
      }
    };

    loadExistingItinerary();
  }, [tripId, aiItinerary, loadingAiItinerary]);

  // Check total activities count across all days
  useEffect(() => {
    if (!tripId || !days || days.length === 0) {
      setAllActivitiesCount(null);
      return;
    }

    const checkAllActivities = async () => {
      const { count, error } = await supabase
        .from("activities")
        .select("id", { count: "exact", head: true })
        .in("day_id", days.map(d => d.id));

      if (error) {
        console.error("Error checking activities:", error);
        setAllActivitiesCount(null);
      } else {
        setAllActivitiesCount(count || 0);
      }
    };

    checkAllActivities();
  }, [tripId, days, supabase]);

  // Auto-generate itinerary if no activities exist across all days and we haven't tried yet
  const generateItinerary = useCallback(async () => {
    setLoadingAiItinerary(true);
    setAiItineraryError(null);
    try {
      const response = await fetch("/api/ai-itinerary", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ tripId }),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || "Failed to generate itinerary");
      }

      const { itinerary } = await response.json();
      setAiItinerary(itinerary);
      // Invalidate activities query to show new activities in the list if user switches to edit mode
      queryClient.invalidateQueries({ queryKey: ["activities"] });
      // Refresh trip to get the stored itinerary JSON
      queryClient.invalidateQueries({ queryKey: ["trip", tripId] });
    } catch (error) {
      console.error("Error generating AI itinerary:", error);
      setAiItineraryError(
        error instanceof Error
          ? error.message
          : "Failed to generate itinerary. Please try again."
      );
    } finally {
      setLoadingAiItinerary(false);
    }
  }, [tripId, queryClient]);

  useEffect(() => {
    if (
      trip &&
      days &&
      days.length > 0 &&
      allActivitiesCount !== null &&
      allActivitiesCount === 0 &&
      !aiItinerary &&
      !loadingAiItinerary &&
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true;
      generateItinerary();
    }
  }, [trip, days, allActivitiesCount, aiItinerary, loadingAiItinerary, generateItinerary]);

  // Fetch route legs when activities change (only relevant for manual view)
  useEffect(() => {
    if (!activities || activities.length === 0) {
      setRouteLegs([]);
      return;
    }

    const activitiesWithValidPlaces = activities
      .filter(
        (activity) =>
          activity.place &&
          activity.place.lat != null &&
          activity.place.lng != null &&
          !isNaN(activity.place.lat) &&
          !isNaN(activity.place.lng)
      )
      .map((activity) => ({
        id: activity.id,
        place: {
          lat: activity.place!.lat!,
          lng: activity.place!.lng!,
        },
      }));

    if (activitiesWithValidPlaces.length < 2) {
      setRouteLegs([]);
      return;
    }

    getDayRoute(activitiesWithValidPlaces).then((result) => {
      setRouteLegs(result.legs);
    });
  }, [activities]);

  const handleAddActivity = () => {
    setEditingActivity(null);
    setActivityDialogOpen(true);
  };

  const handleEditActivity = (activityId: string) => {
    const activity = activities.find((a) => a.id === activityId);
    setEditingActivity(activity);
    setActivityDialogOpen(true);
  };

  const handleDeleteActivity = async (activityId: string) => {
    if (confirm("Are you sure you want to delete this activity?")) {
      await deleteActivity.mutateAsync(activityId);
    }
  };

  const handleSubmitActivity = async (activityData: any) => {
    if (!selectedDayId) return;

    const maxOrder = Math.max(
      0,
      ...activities.map((a) => a.order_number || 0)
    );

    if (editingActivity) {
      await updateActivity.mutateAsync({
        id: editingActivity.id,
        ...activityData,
      });
    } else {
      await createActivity.mutateAsync({
        ...activityData,
        day_id: selectedDayId,
        order_number: maxOrder + 1,
      });
    }

    setActivityDialogOpen(false);
    setEditingActivity(null);
  };

  const handleSelectActivity = (activityId: string) => {
    if (onActivitySelect) {
      onActivitySelect(activityId);
    }
  };

  const handleDeleteTrip = async () => {
    if (!trip) return;

    try {
      const { error } = await supabase
        .from("trips")
        .delete()
        .eq("id", tripId);

      if (error) throw error;

      router.push("/trips");
    } catch (error) {
      console.error("Error deleting trip:", error);
      addToast({
        variant: "destructive",
        title: "Failed to delete trip",
        description: "Please try again.",
      });
    }
  };

  // Close settings menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (settingsMenuRef.current && !settingsMenuRef.current.contains(event.target as Node)) {
        setSettingsMenuOpen(false);
      }
    };

    if (settingsMenuOpen) {
      document.addEventListener("mousedown", handleClickOutside);
      return () => document.removeEventListener("mousedown", handleClickOutside);
    }
  }, [settingsMenuOpen]);

  const loadChatMessages = useCallback(async (limit: number = 20, offset: number = 0) => {
    setLoadingChatMessages(true);
    const { data, error, hasMore } = await getChatMessages(tripId, limit, offset);
    if (!error && data) {
      if (offset === 0) {
        setChatMessages(data);
      } else {
        setChatMessages((prev) => [...data, ...prev]);
      }
      setChatHasMore(hasMore);
    }
    setLoadingChatMessages(false);
  }, [tripId]);

  // Load chat messages on mount
  useEffect(() => {
    if (tripId && chatMessages.length === 0) {
      loadChatMessages(20, 0);
    }
  }, [tripId, loadChatMessages, chatMessages.length]);

  // Scroll to bottom when new messages arrive
  useEffect(() => {
    if (chatMessagesEndRef.current) {
      setTimeout(() => {
        chatMessagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
      }, 100);
    }
  }, [chatMessages]);

  const handleSendChat = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim() || sendingChat) return;

    const userMessage = chatInput.trim();
    setChatInput("");
    setSendingChat(true);

    const tempUserMessage: ChatMessage = {
      id: `temp-${Date.now()}`,
      trip_id: tripId,
      role: "user",
      content: userMessage,
      created_at: new Date().toISOString(),
    };
    setChatMessages((prev) => [...prev, tempUserMessage]);

    try {
      const response = await fetch(`/api/trips/${tripId}/chat`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ message: userMessage }),
      });

      if (!response.ok) {
        throw new Error("Failed to send message");
      }

      const { message: assistantMessage } = await response.json();

      setChatMessages((prev) => {
        const withoutTemp = prev.filter((m) => !m.id.startsWith("temp-"));
        const tempAssistantMessage: ChatMessage = {
          id: `temp-assistant-${Date.now()}`,
          trip_id: tripId,
          role: "assistant",
          content: assistantMessage,
          created_at: new Date().toISOString(),
        };
        return [...withoutTemp, tempAssistantMessage];
      });

      await loadChatMessages(20, 0);
    } catch (error) {
      console.error("Error sending chat message:", error);
      addToast({
        title: "Error",
        description: "Failed to send message. Please try again.",
        variant: "destructive",
      });
      setChatMessages((prev) => {
        const withoutTemp = prev.filter((m) => !m.id.startsWith("temp-"));
        const errorMessage: ChatMessage = {
          id: `error-${Date.now()}`,
          trip_id: tripId,
          role: "assistant",
          content: "Failed – please try again",
          created_at: new Date().toISOString(),
        };
        return [...withoutTemp, errorMessage];
      });
    } finally {
      setSendingChat(false);
    }
  };

  if (tripLoading || daysLoading) {
    return (
      <div className="p-6">
        <div className="text-muted-foreground">Loading...</div>
      </div>
    );
  }

  if (!trip || !days || days.length === 0) {
    return (
      <div className="p-6">
        <div className="text-muted-foreground">No trip data found</div>
      </div>
    );
  }

  return (
    <div className="p-6 h-full flex flex-col overflow-hidden bg-gray-50/50">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-start justify-between mb-2">
          <div className="flex-1">
            <h1 className="text-2xl font-bold">{trip.title}</h1>
            <p className="text-sm text-muted-foreground">
              {format(new Date(trip.start_date), "MMM d")} -{" "}
              {format(new Date(trip.end_date), "MMM d, yyyy")}
            </p>
          </div>
          <div className="flex gap-2 items-center">
            <Button
              variant="outline"
              onClick={() => setMembersDialogOpen(true)}
              className="flex items-center gap-2"
            >
              <Users className="h-4 w-4" />
              <span>Tripmates</span>
            </Button>
            <Button
              variant="outline"
              size="icon"
              onClick={() => setShareDialogOpen(true)}
              title="Share Trip"
            >
              <Share2 className="h-4 w-4" />
            </Button>
            {trip.owner_id === userId && (
              <div className="relative" ref={settingsMenuRef}>
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => setSettingsMenuOpen(!settingsMenuOpen)}
                  title="Trip Settings"
                >
                  <MoreVertical className="h-4 w-4" />
                </Button>
                {settingsMenuOpen && (
                  <div className="absolute right-0 mt-2 w-48 bg-background border rounded-md shadow-lg z-10">
                    <button
                      onClick={() => {
                        setSettingsMenuOpen(false);
                        setDeleteDialogOpen(true);
                      }}
                      className="w-full text-left px-4 py-2 text-sm text-destructive hover:bg-muted flex items-center gap-2"
                    >
                      <Trash2 className="h-4 w-4" />
                      Delete trip
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Hotel Banner */}
      <HotelSearchBanner tripId={tripId} className="mb-6" />

      {/* Content Area */}
      <div className="flex-1 overflow-hidden flex flex-col">
        <div className="flex-1 overflow-y-auto pr-2">
        
        {/* Loading State Card */}
        {loadingAiItinerary && (
          <Card className="mb-6 border-2 border-purple-300 bg-gradient-to-br from-purple-50 to-purple-100 shadow-lg rounded-2xl">
            <CardContent className="flex flex-col items-center justify-center py-12">
              <Loader2 className="h-10 w-10 animate-spin text-purple-600 mb-4" />
              <h3 className="text-lg font-bold text-purple-900">
                We&apos;re crafting your story-like itinerary...
              </h3>
              <p className="text-sm text-purple-700 mt-2 max-w-sm text-center">
                Using AI to find the best spots, photos, and schedule for your trip.
              </p>
            </CardContent>
          </Card>
        )}

        {aiItineraryError && (
          <div className="text-sm text-destructive p-3 bg-destructive/10 rounded-md border border-destructive/20 mb-6">
            {aiItineraryError}
          </div>
        )}

        {/* Smart Itinerary View */}
        {aiItinerary ? (
          <div className="space-y-8 pb-10">
            {/* Intro Card */}
            <Card className="bg-gradient-to-br from-white to-gray-50 border-none shadow-sm ring-1 ring-black/5">
              <CardHeader>
                <CardTitle className="text-3xl font-bold text-gray-900 mb-2">
                  {aiItinerary.tripTitle}
                </CardTitle>
                <CardDescription className="text-lg leading-relaxed text-gray-700">
                  {aiItinerary.summary}
                </CardDescription>
              </CardHeader>
            </Card>

            {/* Days */}
            {aiItinerary.days.map((day, dayIdx) => {
              // Extract all activities with photos from this day for the strip
              const activitiesWithPhotos: ActivitySuggestion[] = []
              day.sections.forEach(section => {
                section.suggestions.forEach(suggestion => {
                  if (isActivitySuggestion(suggestion) && suggestion.photoUrl) {
                    // Avoid duplicates by URL
                    if (!activitiesWithPhotos.some(a => a.photoUrl === suggestion.photoUrl)) {
                      activitiesWithPhotos.push(suggestion);
                    }
                  }
                })
              });
              
              // Limit to 4 photos
              const displayPhotos = activitiesWithPhotos.slice(0, 4);

              return (
                <Card key={dayIdx} className="overflow-hidden border-none shadow-md ring-1 ring-black/5">
                  <CardHeader className="bg-white border-b pb-4">
                    <div className="flex flex-col md:flex-row md:justify-between md:items-end gap-2">
                      <div>
                        <CardTitle className="text-xl font-bold text-gray-900">
                          Day {dayIdx + 1} – {day.title}
                        </CardTitle>
                        <CardDescription className="text-base mt-1 font-medium text-primary/80">
                          {format(new Date(day.date), "EEEE, MMMM d")} • {day.theme}
                        </CardDescription>
                      </div>
                    </div>
                  </CardHeader>
                  
                  <CardContent className="p-0">
                    {/* Photo Strip */}
                    {displayPhotos.length > 0 && (
                      <div className="w-full h-40 flex overflow-x-auto scrollbar-hide bg-gray-100">
                        {displayPhotos.map((photo, idx) => (
                          <div key={idx} className="relative h-full min-w-[200px] flex-1 first:pl-0">
                            <Image
                              src={photo.photoUrl!}
                              alt={photo.title}
                              fill
                              className="object-cover border-r border-white/20"
                              unoptimized
                            />
                            <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-2">
                              <p className="text-white text-xs font-medium truncate">{photo.title}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    <div className="p-6 space-y-8 bg-white">
                      {day.sections.map((section, sectionIdx) => (
                        <div key={sectionIdx} className="relative pl-4 border-l-2 border-gray-100">
                          <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-primary/20 border-2 border-white ring-1 ring-primary/40" />
                          
                          <h4 className="font-bold text-lg text-gray-900 mb-2">
                            {section.partOfDay}
                          </h4>
                          
                          <p className="text-sm text-gray-600 mb-4 leading-relaxed">
                            {section.description}
                          </p>
                          
                          <div className="space-y-3">
                            {section.suggestions.map((suggestion, sugIdx) => {
                              const activity = isActivitySuggestion(suggestion) ? suggestion : null
                              const title = activity ? activity.title : String(suggestion)
                              const goodFor = activity?.goodFor
                              const photoUrl = activity?.photoUrl
                              const placeKey = `${dayIdx}-${sectionIdx}-${sugIdx}`
                              const isVisited = visitedPlaces.has(placeKey)

                              return (
                                <div 
                                  key={sugIdx} 
                                  className={`flex items-start gap-3 p-3 rounded-lg hover:bg-gray-50 transition-colors group ${isVisited ? 'opacity-60' : ''}`}
                                >
                                  {photoUrl ? (
                                    <div className="relative flex-shrink-0 w-16 h-16 rounded-md overflow-hidden shadow-sm">
                                      <Image
                                        src={photoUrl}
                                        alt={title}
                                        fill
                                        className="object-cover group-hover:scale-105 transition-transform duration-500"
                                        unoptimized
                                      />
                                    </div>
                                  ) : (
                                    <div className="flex-shrink-0 w-16 h-16 rounded-md bg-gray-100 flex items-center justify-center text-gray-400 shadow-sm">
                                      <MapPin size={20} />
                                    </div>
                                  )}
                                  <div className="flex-1 min-w-0 py-1">
                                    <div className="flex items-start justify-between gap-2">
                                      <div className="flex-1">
                                        <h5 className="font-medium text-gray-900 flex items-center gap-2">
                                          {title}
                                          {isVisited && <Check className="h-4 w-4 text-green-600" />}
                                        </h5>
                                        {goodFor && (
                                          <p className="text-xs text-primary mt-1 font-medium">
                                            {goodFor}
                                          </p>
                                        )}
                                        {/* Placeholder for rating - can be enhanced when rating data is available */}
                                        {/* {rating && (
                                          <p className="text-xs text-gray-500 mt-1 flex items-center gap-1">
                                            <Star className="h-3 w-3 fill-yellow-400 text-yellow-400" />
                                            {rating} · {userRatingsTotal} reviews
                                          </p>
                                        )} */}
                                      </div>
                                      <div className="flex items-center gap-1">
                                        <Button
                                          variant="ghost"
                                          size="sm"
                                          className="h-8 w-8 p-0"
                                          onClick={() => {
                                            setVisitedPlaces(prev => {
                                              const next = new Set(prev)
                                              if (next.has(placeKey)) {
                                                next.delete(placeKey)
                                              } else {
                                                next.add(placeKey)
                                              }
                                              return next
                                            })
                                          }}
                                          title={isVisited ? "Mark as not visited" : "Mark as visited"}
                                        >
                                          {isVisited ? (
                                            <Check className="h-4 w-4 text-green-600" />
                                          ) : (
                                            <Check className="h-4 w-4 text-gray-400" />
                                          )}
                                        </Button>
                                        <Button
                                          variant="ghost"
                                          size="sm"
                                          className="h-8 w-8 p-0 text-gray-400 hover:text-destructive"
                                          onClick={() => {
                                            // Remove from day - update local state
                                            const updatedItinerary = { ...aiItinerary! }
                                            const day = updatedItinerary.days[dayIdx]
                                            const section = day.sections[sectionIdx]
                                            section.suggestions = section.suggestions.filter((_, idx) => idx !== sugIdx)
                                            setAiItinerary(updatedItinerary)
                                          }}
                                          title="Remove from day"
                                        >
                                          <X className="h-4 w-4" />
                                        </Button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              )
                            })}
                          </div>
                          
                          {section.seasonalNotes && (
                            <div className="mt-4 text-xs text-amber-600 bg-amber-50 p-3 rounded-md border border-amber-100 inline-block">
                              ✨ {section.seasonalNotes}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              )
            })}
          </div>
        ) : (
          // Fallback / Manual View
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold">Daily Activities</h3>
              <Button 
                onClick={handleAddActivity} 
                size="sm"
                className="bg-orange-500 hover:bg-orange-600 text-white border-2 border-black rounded-xl"
              >
                <Plus className="mr-2 h-4 w-4" />
                Add Activity
              </Button>
            </div>
            
            <DaySelector
              days={days}
              selectedDayId={selectedDayId}
              onSelectDay={onSelectDay}
            />
            
            {selectedDayId ? (
              <ActivityList
                activities={activities}
                routeLegs={routeLegs}
                onEdit={handleEditActivity}
                onDelete={handleDeleteActivity}
                onSelect={handleSelectActivity}
              />
            ) : (
              <div className="text-sm text-muted-foreground py-12 text-center bg-white rounded-lg border border-dashed">
                Select a day to view activities
              </div>
            )}
          </div>
        )}

        {/* Chat Panel - Bottom of Itinerary Tab */}
        <div className="border-t bg-white shadow-lg flex flex-col" style={{ maxHeight: '300px' }}>
          <div className="px-4 py-2 border-b bg-gray-50">
            <h3 className="text-sm font-semibold text-gray-900">Trip Assistant – Ask about your itinerary</h3>
          </div>
          <div className="flex-1 overflow-y-auto p-4 space-y-4 min-h-0" style={{ maxHeight: '200px' }}>
            {chatHasMore && (
              <div className="text-center">
                <button
                  onClick={() => loadChatMessages(20, chatMessages.length)}
                  disabled={loadingChatMessages}
                  className="text-xs text-muted-foreground hover:underline"
                >
                  {loadingChatMessages ? "Loading..." : "Load earlier messages"}
                </button>
              </div>
            )}
            {chatMessages.length === 0 && !loadingChatMessages && (
              <div className="text-sm text-muted-foreground text-center py-4 px-4">
                Ask me anything about your trip! I can suggest places, check opening hours, or help you adjust your plans.
              </div>
            )}
            {chatMessages.map((msg) => {
              const isError = msg.id.startsWith("error-");
              const isUser = msg.role === "user";
              
              return (
                <div
                  key={msg.id}
                  className={`flex ${isUser ? "justify-end" : "justify-start"}`}
                >
                  <div className="flex flex-col max-w-[85%]">
                    <div
                      className={`rounded-2xl px-4 py-2 text-sm ${
                        isUser
                          ? "bg-primary text-primary-foreground rounded-tr-none"
                          : isError
                          ? "bg-destructive/10 text-destructive border border-destructive/20"
                          : "bg-gray-100 text-gray-800 rounded-tl-none"
                      }`}
                    >
                      <p className="whitespace-pre-wrap">{msg.content}</p>
                    </div>
                  </div>
                </div>
              );
            })}
            {sendingChat && (
              <div className="flex justify-start">
                <div className="bg-gray-100 rounded-2xl rounded-tl-none px-4 py-3">
                  <div className="flex items-center gap-1">
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />
                  </div>
                </div>
              </div>
            )}
            <div ref={chatMessagesEndRef} />
          </div>
          <div className="p-3 border-t bg-gray-50">
            <form onSubmit={handleSendChat} className="flex gap-2">
              <Input
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="Type a message..."
                disabled={sendingChat}
                className="flex-1 bg-white"
              />
              <Button 
                type="submit" 
                disabled={sendingChat || !chatInput.trim()} 
                size="icon"
              >
                <Send className="h-4 w-4" />
              </Button>
            </form>
          </div>
        </div>
      </div>

      {/* Dialogs */}
      {selectedDayId && (
        <ActivityDialog
          open={activityDialogOpen}
          onOpenChange={setActivityDialogOpen}
          onSubmit={handleSubmitActivity}
          initialData={editingActivity}
          dayId={selectedDayId}
        />
      )}

      <ShareTripDialog
        open={shareDialogOpen}
        onOpenChange={setShareDialogOpen}
        tripId={tripId}
      />

      <TripMembersDialog
        open={membersDialogOpen}
        onOpenChange={setMembersDialogOpen}
        tripId={tripId}
        userId={userId}
      />

      <DeleteTripDialog
        open={deleteDialogOpen}
        onOpenChange={setDeleteDialogOpen}
        onConfirm={handleDeleteTrip}
        tripTitle={trip.title}
      />
    </div>
  );
}
